services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_POCKETBASE_URL: http://localhost:8090
        NEXT_PUBLIC_N8N_WEBHOOK_URL: http://localhost:5678
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
      - n8n
    stop_grace_period: 1m
    restart: unless-stopped
    networks:
      - linkedout-network
    extra_hosts:
      - "localhost:127.0.0.1"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"

  pocketbase:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL:-admin@example.com}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD:-changeme123}
    volumes:
      - ./backend/pb_data:/pb_data
    restart: unless-stopped
    networks:
      - linkedout-network

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_PATH=/
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PUBLIC_API_DISABLED=false
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678/}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-false}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - linkedout-network

  # Optional: Keep ngrok if you need it
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: "http n8n:5678"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"  # ngrok web interface
    depends_on:
      - n8n
    networks:
      - linkedout-network

volumes:
  pb_data:
  n8n_data:

networks:
  linkedout-network:
    name: linkedout-network